export const USER_ROLES = {
  ADMIN: "ADMIN",
  CUSTOMER: "CUSTOMER",
  INVENTORY_MANAGER: "INVENTORY_MANAGER",
  SALES_STAFF: "SALES_STAFF",
  DELIVERY_STAFF: "DELIVERY_STAFF",
} as const;

export type UserRole = (typeof USER_ROLES)[keyof typeof USER_ROLES];

export const ADMIN_ROLES: UserRole[] = [
  USER_ROLES.ADMIN,
  USER_ROLES.INVENTORY_MANAGER,
  USER_ROLES.SALES_STAFF,
  USER_ROLES.DELIVERY_STAFF,
];

export const STAFF_ROLES: UserRole[] = [
  USER_ROLES.ADMIN,
  USER_ROLES.INVENTORY_MANAGER,
  USER_ROLES.SALES_STAFF,
  USER_ROLES.DELIVERY_STAFF,
];
